# -*-python-*-

Import("env")

py_dir = '../openalea/draco_stem' if 'openalea' else '../draco_stem'

# Build wrappers as shared libraries
# First wrapper
env1 = env.Clone()

sources = env1.ALEAGlob('*.cpp')
target = "_draco_stem"
lib = ["draco_stem"]

env1.AppendUnique(LIBS=lib)
env1.ALEAWrapper(py_dir, target, sources)


