# -*-python-*-

Import("env")

py_dir = '../openalea/mesh' if 'openalea' else '../mesh'

# Build wrappers as shared libraries
# First wrapper
env1 = env.Clone()

sources = env1.ALEAGlob('*.cpp')
target = "_mesh"
lib = ["mesh"]

env1.AppendUnique(LIBS=lib)
env1.ALEAWrapper(py_dir, target, sources)


