# -*-python-*-

Import("env")

py_dir = '../openalea/cgal_meshing' if 'openalea' else '../cgal_meshing'

# Build wrappers as shared libraries
# First wrapper
env1 = env.Clone()

sources = env1.ALEAGlob('*.cpp')
target = "_cgal_meshing"
lib = ["cgal_meshing"]

env1.AppendUnique(LIBS=lib)
env1.ALEAWrapper(py_dir, target, sources)


