import openalea.cellcomplex.property_topomesh.property_topomesh_optimization
reload(openalea.cellcomplex.property_topomesh.property_topomesh_optimization) 
from openalea.cellcomplex.property_topomesh.property_topomesh_optimization import *