# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'mesh'
__version__ = '1.0.0'
__license__ = 'CeCILL-C'
__author__ = None
__institutes__ = None
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = ''
__alias__ = []

__all__ = []


draco_init = Factory(name='draco_initialization',
                description='Initialize a DracoMesh using an image',
                category='draco_stem',
                nodemodule='openalea.draco_stem.draco.draco',
                nodeclass='draco_initialization',
                inputs=[dict(interface="IImage",name='image',value=None), 
                        dict(interface="IFileStr",name='image_file',value=None),
                        dict(interface="IFileStr",name='cell_vertex_file',value=None)],
                outputs=[dict(interface=None,name='draco')],
                widgetmodule=None,
                widgetclass=None,
               )
__all__.append("draco_initialization")


draco_image = Factory(name='draco_image',
                description='Get the image of a DracoMesh',
                category='draco_stem',
                nodemodule='openalea.draco_stem.draco.draco',
                nodeclass='draco_segmented_image',
                inputs=[dict(interface=None,name='draco',value=None)],
                outputs=[dict(interface="IImage",name='segmented_image',value=None)],
                widgetmodule=None,
                widgetclass=None,
               )
__all__.append("draco_image")

# topomesh_triangular_mesh = Factory(name='topomesh_triangular_mesh',
#                 description='''Convert a PropertyTopomesh into a displayable mesh''',
#                 category='image',
#                 nodemodule='openalea.mesh.triangular_mesh',
#                 nodeclass='topomesh_to_triangular_mesh',
#                 inputs=[dict(interface=None,name='topomesh',value=None), 
#                         dict(interface='IInt',name='degree',value=3), 
#                         dict(interface='IFloat',name='coef',value=1.0), 
#                         dict(interface='ITuple',name='mesh_center',value=(0.0,0.0,0.0)), 
#                         dict(interface='IBool',name='epidermis',value=False),
#                         dict(interface='IStr',name='property_name',value=None,hide=True), 
#                         dict(interface='IInt',name='property_degree',value=None,hide=True), ],
#                 outputs=[dict(interface=None,name='topomesh_triangular_mesh'),
#                          dict(interface=None,name='triangle_topomesh_cells',hide=True),
#                          dict(interface=None,name='triangle_topomesh_triangles',hide=True),],
#                 widgetmodule=None,
#                 widgetclass=None,
#                )
# __all__.append("topomesh_triangular_mesh")
    

# cell_vertex_extraction = Factory(name='cell_vertex_extraction',
#                 description= '''Extract the cell vertices from a labelled segmented image_cell_vertex

#                                     Identifies in the image the voxels for which 4 labels or more are represented in the 26-neighborhood and returns a dictionnary with the cells 4-uples as keys and the (average) position of the cell vertices as values
#                                 ''',
#                 category='image',
#                 nodemodule='openalea.mesh.utils.tissue_analysis_tools',
#                 nodeclass='cell_vertex_extraction',
#                 inputs=[dict(interface=None,name='segmented_image',value=None),],
#                 outputs=[dict(interface="IDict",name='image_cell_vertex',value=None),],
#                 widgetmodule=None,
#                 widgetclass=None,
#                )
# __all__.append("cell_vertex_extraction")
