# -*-python-*-

Import("env")

py_dir = '../openalea/cellcomplex' if 'openalea' else '../cellcomplex'

# Build wrappers as shared libraries
# First wrapper
env1 = env.Clone()

sources = env1.ALEAGlob('*.cpp')
target = "_cellcomplex"
lib = ["cellcomplex"]

env1.AppendUnique(LIBS=lib)
env1.ALEAWrapper(py_dir, target, sources)


